#server:
#  port: 8070
#基础组件配置
logs:
  #本地调试开启日志
  svcperform:
    enable: true  #是否开启性能日志
    printResult: true  #是否打印输出结果
#hystrix: 
#  command: 
#    callOperaRsp: #注解中的commandKey属性值,如有特殊配置不想使用默认配置可自行添加
#     execution: 
#      isolation: 
#        thread: 
#          timeoutInMilliseconds: 10000 #执行超时时间    
#web: 
#  rest: 
#    svcdomains-layout: 
#      #- domain: acting
#      - domain: users
#        ip: localhost #相同配置svcdomains-layout优先级高于svcdomains
#        port: 8080
#        readTimeout: 10000
